# Generated by Django 2.2.1 on 2019-05-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=25, null=True, verbose_name='nickname')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=2, verbose_name='language')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone')),
                ('is_attending', models.NullBooleanField(default=None, help_text='Are you attending?', verbose_name='is attending')),
                ('is_child', models.BooleanField(default=False, help_text='Under 12', verbose_name='is child')),
                ('receive_updates', models.BooleanField(default=True, help_text='Even if you are not attending, we can keep you in the loop with photos, etc.', verbose_name='receive updates')),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True)),
                ('has_car', models.BooleanField(default=False)),
                ('dietary_restrictions', models.TextField(blank=True, default=None, null=True)),
                ('comes_from', models.TextField(blank=True, default=None, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='ourwedding.Group')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_attending'],
            },
        ),
        migrations.CreateModel(
            name='MessageFromGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('opened', models.BooleanField(default=False)),
                ('opened_on', models.DateTimeField(default=None, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('notified_on', models.DateTimeField(default=None, null=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('is_attending', models.NullBooleanField(default=None, help_text='Are you attending?', verbose_name='is attending')),
                ('is_child', models.BooleanField(default=False, help_text='Under 12', verbose_name='is child')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone')),
                ('has_car', models.BooleanField(default=False)),
                ('comes_from', models.TextField(blank=True, default=None, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anecdote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(verbose_name='message')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ourwedding.Profile')),
            ],
            options={
                'verbose_name': 'anecdote',
                'verbose_name_plural': 'anecdotes',
                'ordering': ['-timestamp'],
                'get_latest_by': '-timestamp',
            },
        ),
    ]
