# Generated by Django 2.2.4 on 2019-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourwedding', '0005_guest_needs_van'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='post_wedding',
            field=models.BooleanField(default=False, help_text='Are you attending the post-wedding?', verbose_name='post wedding'),
        ),
        migrations.AddField(
            model_name='guest',
            name='pre_wedding',
            field=models.BooleanField(default=False, help_text='Are you attending the pre-wedding?', verbose_name='pre wedding'),
        ),
    ]
