# Generated by Django 2.2.4 on 2019-09-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtokens',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
